version: '3.4'
services:
  main:
    environment:
      - UID=${HOST_UID:-0}
      - USER=${HOST_USER:-root}
      - USER_HOME=${USER_HOME:-/root}
    user: ${HOST_USER:-root}
    build:
      context: jupyter
      args:
        - HOST_UID=${HOST_UID:-0}
        - HOST_USER=${HOST_USER:-root}
        - USER_HOME=${USER_HOME:-/root}
    ports:
      - "8888:8888"
    volumes:
      - ${WORKDIR}:${USER_HOME}/notebooks
