FROM python:3.8-slim-buster

# RUN apt-get update --fix-missing \
RUN apt-get -y install --no-install-recommends 
RUN sleep 5000
RUN apt-get -y install bash
RUN apt-get -y install iputils-ping

WORKDIR /app
